"""Test Relations Migration

Revision ID: b538ee92e8c3
Revises: d2f3338e86a0
Create Date: 2020-12-12 17:40:21.402964

"""
from alembic import op
import sqlalchemy as sa
import backend


# revision identifiers, used by Alembic.
revision = 'b538ee92e8c3'
down_revision = 'd2f3338e86a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_cases', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'test_cases', 'test_cases', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_cases', type_='foreignkey')
    op.drop_column('test_cases', 'parent_id')
    # ### end Alembic commands ###
