"""Initial Migration

Revision ID: d2f3338e86a0
Revises: 
Create Date: 2020-12-12 17:17:15.595752

"""
from alembic import op
import sqlalchemy as sa
import backend


# revision identifiers, used by Alembic.
revision = 'd2f3338e86a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('request_method', sa.String(length=10), nullable=True),
    sa.Column('request_headers', backend.system.db.types.JSONEncodedDict(), nullable=True),
    sa.Column('request_body', sa.Text(), nullable=True),
    sa.Column('request_data_type', backend.system.db.types.IntEnum(), nullable=True),
    sa.Column('response_headers', backend.system.db.types.JSONEncodedDict(), nullable=True),
    sa.Column('response_body', backend.system.db.types.JSONEncodedDict(), nullable=True),
    sa.Column('response_data_type', backend.system.db.types.IntEnum(), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('readable_name', sa.String(length=255), nullable=True),
    sa.Column('module', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_suites',
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.String(length=255), nullable=True),
    sa.Column('db', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_cases',
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('suite_id', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.ForeignKeyConstraint(['suite_id'], ['test_suites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_cases')
    op.drop_table('test_suites')
    op.drop_table('requests')
    # ### end Alembic commands ###
